- type: playTimeTracker
  id: InteQVanguardLeader

- type: playTimeTracker
  id: InteQVanguard

- type: playTimeTracker
  id: JobERTInteQVanguardLeader

- type: playTimeTracker
  id: JobERTInteQVanguard

- type: playTimeTracker
  id: JobCBURNLeader

- type: playTimeTracker
  id: JobDeathSquadLeader
