- type: job
  id: InteQVanguardLeader
  name: job-name-inteq-vanguard-leader
  description: job-description-inteq-vanguard-leader
  playTimeTracker: InteQVanguardLeader
  setPreference: false
  icon: "JobIconInteQLeader"
  supervisors: job-supervisors-hire
  canBeAntag: false
  access:
  - InteQVanguard
  - InteQVanguardLeader
  - Maintenance

- type: job
  id: InteQVanguard
  name: job-name-inteq-vanguard
  description: job-description-inteq-vanguard
  playTimeTracker: InteQVanguard
  setPreference: false
  icon: "JobIconInteQ"
  supervisors: job-supervisors-hire
  canBeAntag: false
  access:
  - InteQVanguard
  - Maintenance

- type: job # !!!ERT!!!
  id: ERTInteQVanguardLeader
  name: job-name-ert-inteq-vanguard-leader
  description: job-description-inteq-vanguard-leader
  playTimeTracker: JobERTInteQVanguardLeader
  setPreference: false
  icon: "JobIconInteQLeader"
  supervisors: job-supervisors-hire
  canBeAntag: false
  accessGroups:
  - InteQ
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: job # !!!ERT!!!
  id: ERTInteQVanguard
  name: job-name-ert-inteq-vanguard
  description: job-description-inteq-vanguard
  playTimeTracker: JobERTInteQVanguard
  setPreference: false
  icon: "JobIconInteQ"
  supervisors: job-supervisors-hire
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - InteQVanguard
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
